Add org.jooq:joou-java-6 to ql/pom.xml to resolve init-metastore CI error: Caused by: java.lang.NoClassDefFoundError: org/joou/UShort 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3580) 	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3721) 	at java.base/java.lang.Class.getMethod0(Class.java:3707) 	at java.base/java.lang.Class.getMethod(Class.java:2395) 	at org.apache.calcite.linq4j.tree.Types.lookupMethod(Types.java:288) 	at org.apache.calcite.util.BuiltInMethod.<init>(BuiltInMethod.java:1043) 	at org.apache.calcite.util.BuiltInMethod.<clinit>(BuiltInMethod.java:320) 	at org.apache.calcite.rel.metadata.BuiltInMetadata$PercentageOriginalRows.<clinit>(BuiltInMetadata.java:396) 	... This is required due to "[CALCITE-1466] Support for UNSIGNED types of TINYINT, SMALLINT, INT, BIGINT in type system" (1.41), which added this library in Calcite.
Revert upgrade maven.shade.plugin.version in parent pom (not required for the ASM error)

Review

Adjust test iceberg_bucket_map_join_1.q.out