Revert "CDH-42254: Fix pom dependency for QueryRedactor."
This reverts commit 7594c9b1d9223360b5c5f445abbe50f5f61de849.

Reason for revert: Breaks unit tests by causing NoClassDefFoundError

Change-Id: I6a50024637cc16f1a4808433629b2ffcfaa586f8