Revert "CDH-24225 - Hive Log Redaction work"
This reverts commit a626d66d46b6e472030cdea23e9659f18d411e66.

Reason for revert: Breaks unit tests by causing NoClassDefFoundError

Change-Id: I5aa2f12c9906e0ba87755814fe591b19b643a836