Test adjustments: rowcount changes in TestExplainCBOFormattedCliDriver query24, 30, 38, 54, 81, 87 due to [CALCITE-7083] RelMdDistinctRowCount aggregates implementation problems (1.41)
Test adjustments: udtf_explode.q.out plan with GROUP BY + SORT fixed due to
[CALCITE-6748] RelToSqlConverter returns the wrong result when Aggregate is on Sort (1.39)
(and also array changes due to [CALCITE-6417] Map value constructor and Array value constructor unparsed incorrectly for HiveSqlDialect (1.38))

Test adjustments: vectorized_dynamic_partition_pruning.q.out

Some IS NOT NULL simplifications added, e.g. lossless cast double to int to double + division by non-zero:
UDFToDouble(UDFToInteger((hr / 2.0D))) is not null => hr is not null
due to
[CALCITE-5769] Optimizing 'CAST(e AS t) IS NOT NULL' to 'e IS NOT NULL' (1.35) (only if "lossless" cast)

Some IS NOT NULL simplifications removed, e.g. not lossless cast str to double:
UDFToDouble(hr) is not null => (UDFToDouble(hr) * 2.0D) is not null
due to
[CALCITE-7296] RexSimplify should not simplify IS (NOT) NULL(CAST(10/0 AS BIGINT)) (1.42) (non-lossless cast is considered a non-safe operation, so no simplification is applied)

Test adjustments: subquery_scalar.q.out

Changes around IS [NOT] NULL simplifications:
[CALCITE-5769] Optimizing 'CAST(e AS t) IS NOT NULL' to 'e IS NOT NULL' (1.35) (only if "lossless" cast)
[CALCITE-7296] RexSimplify should not simplify IS (NOT) NULL(CAST(10/0 AS BIGINT)) (1.42)

Also if(..) predicate expanded into equivalent OR due to widened SafeRexVisitor's allowlist (enough that simplifyBooleanCaseGeneric could be applied)
[CALCITE-7032] Simplify 'NULL>ALL (ARRAY[1,2,NULL])' to 'NULL' (1.41)
As a consequence of this simplification, there's a row-count delta in the expression (fallout in Hive's selectivity heuristic)

Add new "case CHAR_LENGTH" in SqlFunctionConverter#buildAST, since a new SqlKind.CHAR_LENGTH has been added (previously length functions had SqlKind.OTHER_FUNCTION) via
[CALCITE-6182] Add LENGTH/LEN function (enabled in Snowflake library) (1.37)

Problem observed in several tests, where lenght(x) function not being evaluated (returning 'length' instead of the actual value), e.g. TestJdbcDriver2#testExprCol:
Illegal conversion to int from column 2 [length]
java.sql.SQLException: Illegal conversion to int from column 2 [length]
	at org.apache.hive.jdbc.HiveBaseResultSet.getInt(HiveBaseResultSet.java:445)
	at org.apache.hive.jdbc.TestJdbcDriver2.testExprCol(TestJdbcDriver2.java:2217)