HIVE-27882: Fix missing classes in standalone jar
Fixes java.lang.NoClassDefFoundError exceptions for the following
classes when using hive-jdbc's standalone jar without other hive or
hadoop jars on the classpath
* org/apache/hive/org/apache/commons/io/input/TeeInputStream
* org/apache/hadoop/fs/impl/AbstractFSBuilderImpl

Also streamlines jar by removing some unneeded dependencies, as
identified with 'mvn dependency:analyze-report' then tested with a
standalone JDBC client.

Restores slf4j and reload4j in the standalone jar so logging works.