Fix testSecondRebuildCanBeIncrementalAfterMajorCompaction
It was failing because of Sarg with:
java.lang.AssertionError: cannot convert SARG literal to class java.lang.Long
	at org.apache.calcite.rex.RexLiteral.getValueAs(RexLiteral.java:1143)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.setSnapShotId(HivePushdownSnapshotFilterRule.java:121)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.visitCall(HivePushdownSnapshotFilterRule.java:104)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.visitCall(HivePushdownSnapshotFilterRule.java:88)
	at org.apache.calcite.rex.RexCall.accept(RexCall.java:189)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule.onMatch(HivePushdownSnapshotFilterRule.java:84)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:337)

On my local machine it also complained about:
Exception in thread "main" java.lang.NoClassDefFoundError: org/locationtech/jts/geom/Geometry
  at org.apache.calcite.sql.type.JavaToSqlTypeConversionRules.<init>(JavaToSqlTypeConversionRules.java:74)
  at org.apache.calcite.sql.type.JavaToSqlTypeConversionRules.<clinit>(JavaToSqlTypeConversionRules.java:41)
  at org.apache.calcite.jdbc.JavaTypeFactoryImpl.createType(JavaTypeFactoryImpl.java:153)

which is similar to the init-metastore failures in upstream Ptests. I added org.locationtech.jts:jts-core:1.19.0
to ql/pom.xml, but not sure if it's the best place to add it.

Tested with:
mvn test -Dtest=org.apache.hadoop.hive.ql.txn.compactor.TestMaterializedViewRebuild#testSecondRebuildCanBeIncrementalAfterMajorCompaction