HivePushdownSnapshotFilterRule fails with AssertionError due to presence of SARG
java.lang.AssertionError: cannot convert SARG literal to class java.lang.Long
	at org.apache.calcite.rex.RexLiteral.getValueAs(RexLiteral.java:1143)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.setSnapShotId(HivePushdownSnapshotFilterRule.java:121)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.visitCall(HivePushdownSnapshotFilterRule.java:104)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule$SnapshotIdShuttle.visitCall(HivePushdownSnapshotFilterRule.java:88)
	at org.apache.calcite.rex.RexCall.accept(RexCall.java:189)
	at org.apache.hadoop.hive.ql.optimizer.calcite.rules.views.HivePushdownSnapshotFilterRule.onMatch(HivePushdownSnapshotFilterRule.java:84)

1. Ensure that SEARCH in filter is expanded before calling HivePushdownSnapshotFilterRule
2. Avoid extra transformations in HivePushdownSnapshotFilterRule when filter condition remains unchanged.

The second change is not only an optimization that will reduce the search space but also a necessary fix to avoid reintroducing SEARCH in the plan by calling RelBuilder#filter method.

The changes were tested using:
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile_regex="materialized_view.*" -Dtest.output.overwrite