execute error with this class
when i use hive-jdbc to get data from hive, i got this exception
org.apache.commons.beanutils.ConversionException: Cannot assign value of type 'java.math.BigDecimal' to property 'valuess' of type 'java.math.BigInteger'
because the data type is decimal
so i change the type to solve it