Add new "case CHAR_LENGTH" in SqlFunctionConverter#buildAST, since a new SqlKind.CHAR_LENGTH has been added (previously length functions had SqlKind.OTHER_FUNCTION) via [CALCITE-6182] Add LENGTH/LEN function (enabled in Snowflake library) (1.37)
Problem observed in several tests, where lenght(x) function not being evaluated (returning 'length' instead of the actual value), e.g. TestJdbcDriver2#testExprCol:
Illegal conversion to int from column 2 [length]
java.sql.SQLException: Illegal conversion to int from column 2 [length]
	at org.apache.hive.jdbc.HiveBaseResultSet.getInt(HiveBaseResultSet.java:445)
	at org.apache.hive.jdbc.TestJdbcDriver2.testExprCol(TestJdbcDriver2.java:2217)