Move CTE rewriting logic in CalcitePlanner before join ordering transformations
The refactoring is desired/necessary for the following reasons:
* Spool sub-plans take advantage of all standard optimization rules leading to more efficient plans. The Spool sub-plans are coming from potentially external tools so we have no guarantees about their shape; as it can be seen by existing plans before this change the plans below a spool operator was far from optimal (presence of cartesian products, missed filter pushdown opportunities, etc.).
* Moving the logic inside CalcitePlanner allows to use existing code for MV rewritting, and individual rule application (using executeProgram
* The ASTConverter along with other code relies on the fact that the plan has a certain shape, which is obtained by applying all rules. If the Spool sub-plan (or other parts of the query) do not adhere to desired structure this can lead to failures. For instance, cbo_query64.q was failing with the following stacktrace due to the unexpected structure under the Spool:
mvn test -Dtest=TestTezTPCDS30TBPerfCliDriver -Dqfile=cbo_query64.q -Dtest.output.overwrite
java.lang.IndexOutOfBoundsException: Index: 92, Size: 7
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_261]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_261]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter$RexVisitor.visitInputRef(ASTConverter.java:709) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter$RexVisitor.visitInputRef(ASTConverter.java:664) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:112) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:354) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convertSource(ASTConverter.java:569) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:261) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convertSource(ASTConverter.java:580) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:261) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convertSource(ASTConverter.java:580) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convertSource(ASTConverter.java:531) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:261) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convertSource(ASTConverter.java:580) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:261) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.optimizer.calcite.translator.ASTConverter.convert(ASTConverter.java:122) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.CalcitePlanner.getOptimizedAST(CalcitePlanner.java:1458) ~[hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.CalcitePlanner.genOPTree(CalcitePlanner.java:627) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:13450) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.CalcitePlanner.analyzeInternal(CalcitePlanner.java:479) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:319) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.ExplainSemanticAnalyzer.analyzeInternal(ExplainSemanticAnalyzer.java:184) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:319) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Compiler.analyze(Compiler.java:227) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Compiler.compile(Compiler.java:108) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:202) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:656) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:602) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:596) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.reexec.ReExecDriver.compileAndRespond(ReExecDriver.java:126) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:232) [hive-exec-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:267) [hive-cli-3.1.3000.2024.0.18.0-12.jar:?]
        at org.apache.hadoop.hive.cli.CliDriver.processCmd1(CliDriver.java:210) [hive-cli-3.1.3000.2024.0.18.0-12.jar:?]
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:136) [hive-cli-3.1.3000.2024.0.18.0-12.jar:?]
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:436) [hive-cli-3.1.3000.2024.0.18.0-12.jar:?]
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:367) [hive-cli-3.1.3000.2024.0.18.0-12.jar:?]
        at org.apache.hadoop.hive.ql.QTestUtil.executeClientInternal(QTestUtil.java:887) [hive-it-util-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.ql.QTestUtil.executeClient(QTestUtil.java:857) [hive-it-util-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.cli.control.CorePerfCliDriver.runTest(CorePerfCliDriver.java:108) [hive-it-util-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.cli.control.CliAdapter.runTest(CliAdapter.java:173) [hive-it-util-3.1.3000.2024.0.18.0-12.jar:3.1.3000.2024.0.18.0-12]
        at org.apache.hadoop.hive.cli.TestTezTPCDS30TBPerfCliDriver.testCliDriver(TestTezTPCDS30TBPerfCliDriver.java:79) [test-classes/:?]

Change-Id: I231bd303611f891b1502760fefcb91dab798e916